# Generated by Django 4.1 on 2022-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('W', 'Web applications'), ('O', 'Others application')], default='W', max_length=1)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('keywords_list', models.CharField(blank=True, max_length=256)),
                ('url_github_oc', models.URLField(blank=True, null=True)),
                ('url_github_portfolio', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects')),
            ],
        ),
    ]
